version: '2'
# we can use docker-compose style services: (see https://docs.docker.com/compose/compose-file/ for docs)
#
services:
  envtest:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
